# This is a basic workflow to help you get started with Actions

name: CSV2ICS

# Controls when the workflow will run
on:
  #schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    #- cron: '40 6 * * *'
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:    
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
    
env:
  SSH: false
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TZ: Asia/Hong_Kong
##on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
 ## push:
   ## branches: [ "main" ]
  ##pull_request:
    ##branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  ##workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      #- name: Run a one-line script
       # run: echo Hello, world!

      
      
      - name: SSH链接管理
        uses: P3TERX/ssh2actions@v1.0.0
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
        env:
         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
         TELEGRAM_CHAT_ID: 1373335316   
      
      
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          pip3 install altgraph easygui icalendar macholib modulegraph py2app python-dateutil pytz six 
          #echo pwd
          ##/home/runner/work/roster/roster/icsconverter.py google_cal_08311.csv
          /home/runner/work/roster/roster/csv2ical.py google_cal_08311.csv 8311.ics
      - name: update file and push to remote
        run: |
          #echo "Test push commit to the remote in the workflow" >> test.txt
          git config --global user.name "harrylwc"
          git config --global user.email "harrylwc@gmail.com"
          #git remote set-url --push origin https://harrylwc@gmail.com:$GITHUB_TOKEN@github.com/harrylwc/roster
          git commit -m "Add changes" -a
          git push https://github.com/harrylwc/roster    
 
          
      - name: SSH connection for testing
        if: env.SSH == 'true'
        uses: P3TERX/ssh2actions@main
        env:
         TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
         TELEGRAM_CHAT_ID: 1373335316          
          
      -  name: SSH connection for failure Debug
         if: ${{ failure() }}
           #uses: lhotari/action-upterm@v1
         uses: P3TERX/ssh2actions@main
         env:
          TELEGRAM_BOT_TOKEN: '5352319218:AAGkspTTlIjIRyfYlI7Egz4NciZ78bT3NF4'
          TELEGRAM_CHAT_ID: '1373335316'
